site_name: pyMultiwfn Documentation
site_url: https://szczypinski-group.github.io/pyMultiwfn/
repo_url: https://github.com/szczypinski-group/pyMultiwfn
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"] # Looking at the root for the pyMultiwfn folder
          options:
            show_root_heading: true
            show_source: true

nav:
  - Home: index.md
  - Use Cases: use_cases.md
  - Contribution Guidelines: contribution.md
  - API Reference:
    - Analysis:
      - Parsers: parsers.md
      - Results: result.md
      - Analysis: analysis.md
    - Core Api Functions:
      - Job Execution: job.md
      - Exceptions: exceptions.md
      - Multiwfn Configuration: multiwfn.md
      - Calculation Outcome: outcome.md
    - Enums:
      - Analysis Classes: analyses.md
      - Menu Sequen`ces: menu.md