[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pymultiwfn"
version = "0.6.0a1"
description = "Python interface and automation toolkit for Multiwfn"
requires-python = ">=3.12"
authors = [
    { name = "Pierre-Louis Valero", email = "ypkh17@durham.ac.uk" },
    { name = "Filip T. Szczypiński", email = "filip.t.szczypinski@durham.ac.uk" },
]

readme = "README.md"
license = "MPL-2.0"
dependencies = [
    "matplotlib>=3.10.8",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
]

[project.urls]
Homepage = "https://szczypinski-group.github.io/pyMultiwfn/"
Documentation = "https://szczypinski-group.github.io/pyMultiwfn/"
Repository = "http://github.com/szczypinski-group/pyMultiwfn/"
Issues = "https://github.com/szczypinski-group/pyMultiwfn/issues"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "interrogate>=1.7.0",
    "nox>=2025.10.16",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.2",
    "ipython>=9.11.0",
]

[tool.hatch.build.targets.sdist]
include = [
  "/src",
  "/tests",
  "LICENSE"
]

[tool.interrogate]
verbose                    = 1
ignore-setters             = true
ignore-property-decorators = true
ignore-magic               = true
ignore-private             = true
ignore-semiprivate         = true
exclude                     = ["tests/**", "menu.py"]

[tool.ruff]
line-length = 79
target-version = "py311"
lint.select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "TD",  # flake8-todos
    "PTH", # flake8-use-pathlib
    "ANN", # flake8-annotations
    "I",   # isort
    "N",   # PEP8 naming
    "D",   # pydocstyle
]
lint.ignore = [
    "D102",  # Missing docstring in public method (interrogate)
    "D103",  # Missing docstring in public function (interrogate)
    "D105",
    "TD003",  # TODO GH issue links are not always possible
]

    [tool.ruff.lint.pydocstyle]
    convention = "numpy"

[tool.mypy]
exclude = "tests/"
