name: Lint Format and Test

on: [push, pull_request]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          enable-cache: true

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest
